services:
  server:
    image: nginx:alpine
    ports:
      - "4443:443"
    networks:
      mitmnet:
        aliases:
          - server
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./certs:/etc/nginx/certs

  mitmproxy:
    image: mitmproxy/mitmproxy
    command: mitmdump --mode reverse:https://server:443 --listen-port 8080 --showhost --ssl-insecure
    tty: true
    stdin_open: true
    depends_on:
      - server
    networks:
      mitmnet:
        aliases:
          - mitmproxy
    ports:
      - "8080:8080"

  client:
    image: curlimages/curl
    depends_on:
      - mitmproxy
    entrypoint: /bin/sh
    stdin_open: true
    tty: true
    networks:
      mitmnet:
        aliases:
          - client

networks:
  mitmnet:
    driver: bridge
